from __future__ import annotations

from datetime import datetime, timezone
from html import escape
from pathlib import Path

from .config import Settings


SUMMARY_FILE_NAME = "world-cup-summary.html"

CURRENT_PLAN = [
    "Generate the World Cup ICS feed and the HTML summary on every run.",
    "Copy the generated artifacts into the local OneDrive project folder on Windows.",
    "Publish the ICS file from a stable public HTTPS URL for Outlook, Apple Calendar, and Google Calendar subscriptions.",
    "Keep deterministic UIDs and sequence tracking so subscribed clients update events instead of duplicating them.",
]

IMPLEMENTED_ACTIONS = [
    "Scaffolded a greenfield Python project in the previously empty repository.",
    "Integrated the openfootball/worldcup source dataset and selected the latest tournament directory automatically.",
    "Parsed only scheduled fixture lines so the calendar contains upcoming World Cup matches.",
    "Generated a deterministic ICS feed with stable event UIDs and persisted sequence state.",
    "Added scheduled refresh automation for 2 PM, 4 PM, 6 PM, and 10 PM Pacific Time.",
    "Configured Windows runs to copy the ICS file into C:\\Users\\thebl\\OneDrive\\Projects\\Zealot.",
    "Added this HTML summary artifact so usage, plan, and implementation details ship with each run.",
]

HOW_TO_USE = [
    "Run python -m world_cup_calendar to regenerate the calendar artifacts.",
    "Use the ICS file for publishing or subscription workflows; do not repeatedly import separate copies if you want update-in-place behavior.",
    "Serve the same world-cup.ics file from a stable URL when you are ready to subscribe from Outlook, Apple Calendar, or Google Calendar.",
    "Open this HTML file in a browser for the current project summary and operating instructions.",
]


def build_summary_html(settings: Settings, event_count: int) -> str:
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")
    output_summary_path = summary_path_for_calendar_path(settings.output_path)
    publish_summary_path = summary_path_for_calendar_path(settings.publish_path) if settings.publish_path else None
    outputs = [
        ("ICS output", settings.output_path),
        ("HTML summary output", output_summary_path),
        ("State file", settings.state_path),
    ]
    if settings.publish_path is not None:
        outputs.append(("Published ICS copy", settings.publish_path))
    if publish_summary_path is not None:
        outputs.append(("Published HTML summary copy", publish_summary_path))

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>World Cup Calendar Summary</title>
  <style>
    body {{
      font-family: Arial, sans-serif;
      line-height: 1.5;
      margin: 0;
      background: #f5f7fb;
      color: #1f2937;
    }}
    main {{
      max-width: 960px;
      margin: 0 auto;
      padding: 32px 20px 48px;
    }}
    section {{
      background: #ffffff;
      border: 1px solid #dbe2ea;
      border-radius: 10px;
      padding: 20px;
      margin-bottom: 18px;
      box-shadow: 0 1px 2px rgba(0, 0, 0, 0.04);
    }}
    h1, h2 {{
      margin-top: 0;
    }}
    code {{
      background: #eef2f7;
      padding: 2px 6px;
      border-radius: 4px;
    }}
    ul {{
      padding-left: 20px;
      margin-bottom: 0;
    }}
    table {{
      width: 100%;
      border-collapse: collapse;
    }}
    th, td {{
      text-align: left;
      border-bottom: 1px solid #e5e7eb;
      padding: 10px 8px;
      vertical-align: top;
    }}
    .meta {{
      color: #4b5563;
      margin-bottom: 20px;
    }}
  </style>
</head>
<body>
  <main>
    <section>
      <h1>World Cup Calendar Project Summary</h1>
      <p class="meta">Generated at {escape(generated_at)} UTC. Current feed contains {event_count} scheduled matches.</p>
      <p>This file is regenerated by <code>python -m world_cup_calendar</code>. If the process changes and the generator runs again, this summary updates with the latest instructions and project state.</p>
    </section>
    <section>
      <h2>How to use the project and files</h2>
      {render_list(HOW_TO_USE)}
    </section>
    <section>
      <h2>Artifacts written by the process</h2>
      {render_outputs_table(outputs)}
    </section>
    <section>
      <h2>Current implementation plan</h2>
      {render_list(CURRENT_PLAN)}
    </section>
    <section>
      <h2>Actions already taken</h2>
      {render_list(IMPLEMENTED_ACTIONS)}
    </section>
    <section>
      <h2>Calendar subscription notes</h2>
      <ul>
        <li>Outlook: use <strong>Add calendar &gt; Subscribe from web</strong> with the final public ICS URL.</li>
        <li>Apple Calendar: use <strong>File &gt; New Calendar Subscription</strong> with the final public ICS URL.</li>
        <li>Google Calendar: use <strong>Other calendars &gt; From URL</strong> with the final public ICS URL.</li>
        <li>Repeated file import creates duplicates. Stable subscription URLs plus stable ICS UIDs are what enable update-in-place behavior.</li>
      </ul>
    </section>
  </main>
</body>
</html>
"""


def summary_path_for_calendar_path(calendar_path: Path) -> Path:
    return calendar_path.with_name(SUMMARY_FILE_NAME)


def render_list(items: list[str]) -> str:
    return "<ul>" + "".join(f"<li>{escape(item)}</li>" for item in items) + "</ul>"


def render_outputs_table(outputs: list[tuple[str, Path]]) -> str:
    rows = "".join(
        f"<tr><th>{escape(label)}</th><td><code>{escape(str(path))}</code></td></tr>"
        for label, path in outputs
    )
    return f"<table>{rows}</table>"

